[[redirects]]
from = "/api/*"
to = "https://www.googleapis.com/youtube/v3/:splat"
status = 200

[[redirects]]
from = "/image/*"
to = "https://i.ytimg.com/vi/:splat"
status = 200

[[redirects]]
from = "/channelImage/*"
to = "https://yt3.ggpht.com/:splat"
status = 200
